[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "WeHostVoIP"
authors = [{name = "Flavio", email = "flavio@wehostvoip.io"}]
dynamic = ["0.9", "Initial Release"]
